


Load Package
```{r}
library(tidyr)
library(tidyverse)
library(rvest)
library(plyr)
library(dplyr)
library(stringr)
#install.packages("tidytext")
# install.packages("unpivotr")
library(unpivotr)
library(tidytext)
```


Load Data
```{r}
MoH <- readRDS("~/Google Drive/OUCRU/Covid-19/MoH_dataset.rds") %>% 
  mutate_all(~str_remove(.,"\n"))
```

When they declare "THONG BAO", they separate paragraphs. I combine the needed information together
```{r}
thongbao <- MoH %>% 
  filter(grepl("THÔNG BÁO", content)) %>% 
  mutate(content = str_replace(content,"\n\n", ":"))

MoH %<>% 
  left_join(thongbao, by = c("date_published"), suffix = c("",".tb")) %>% 
  mutate(content = ifelse(!is.na(content.tb), content.tb, content)) %>% 
  select(-content.tb)
```


Separate paragraphs
```{r}
MoH_df <- MoH %>% 
    unnest_tokens(output = "sentences", input = content,
                token = "regex", pattern = "\n\n|\n|\n \n")  
```

Find which paragraph contains which patient id
```{r}
MoH_df %<>% 
  add_column(id = as.vector(NA)) %>% 
  mutate(id = stringr::str_extract_all(sentences,"bn[:digit:]+-[:digit:]+|bn[:digit:]+")) 
```


Delete rows that don't contain patient id
```{r}
id_row <- which(MoH_df$id != "character(0)")
MoH_df <- MoH_df[id_row,]
```

clean the id column
```{r}
MoH_df %<>% 
  # filter(grepl("-",id)) %>% 
  mutate(id = as.character(id)) %>% 
  mutate(id = str_remove_all(id,"bn")) %>% 
  mutate(id = str_remove_all(id,"c")) %>%
  mutate(id = str_remove_all(id,"\\(|\\)")) %>% 
  mutate(id = str_replace_all(id,"-",",")) %>% 
  mutate(id = noquote(id)) %>% 
  mutate(id = gsub('"', '', id))

MoH_id <- str_split(a$id,",") 

MoH_id <- as.vector(as.numeric(str_trim(unlist(MoH_id), side = c("both"))))


l <- list()
for (i in 1:nrow(MoH_df)) {
  d <- data.frame(c(MoH_df[i,"id"]))
  colnames(d) <- "id"
  d$sentences <- rep(MoH_df[i, "sentences"], nrow(d))
  l[[i]] <- d
}
df <- do.call(rbind, l)


f <- function(x) MoH_df %>% filter(grepl(paste0("\\<",x,"\\>"), id)) %>% pull(sentences)

#dataset with description details for each individual
df1 <- data.frame(id = unique(MoH_id)) %>% 
  mutate(sentences = map(unique(MoH_id), f))
```




filter out rows that have f1
```{r}
MoH_f1<- df1 %>% 
  filter(grepl("f1", sentences)) 
```



Get F1 for each of the row that contais f1
```{r}
# View(MoH_f1)

tidyr::unnest(MoH_f1, cols=c(sentences)) -> MoH_f11
MoH_f11 = within(MoH_f11, {
  senc = stringi::stri_trans_general(sentences, "any-ascii")
})


MoH_f11 %<>% 
    # mutate(f0 = stringr::str_extract_all(senc,r"{(?<=là\sf1\scủa\sbn)\d+}")) %>% 
  mutate(f0 = stringr::str_extract_all(senc,r"{(?<=la\sf1\scua\sbn)\d+}")) %>% 
  view
```









